2018-03-09 04:05:02,646 DEBUG    root            Loaded Command Group: ['gcloud', 'compute', 'forwarding_rules']
2018-03-09 04:05:02,651 DEBUG    root            Loaded Command Group: ['gcloud', 'compute', 'forwarding-rules', 'list']
2018-03-09 04:05:02,654 DEBUG    root            Running [gcloud.compute.forwarding-rules.list] with arguments: []
2018-03-09 04:05:02,753 INFO     root            Display format "        table(
          name,
          region.basename(),
          IPAddress,
          IPProtocol,
          firstof(
              target,
              backendService).scope():label=TARGET
        )
        ".
2018-03-09 04:05:23,020 DEBUG    root            (gcloud.compute.forwarding-rules.list) Some requests did not succeed:
 - Insufficient Permission
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 797, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 759, in Run
    display_info=self.ai.display_info).Display()
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/display.py", line 471, in Display
    self._printer.Print(self._resources)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/resource/resource_printer_base.py", line 254, in Print
    for resource in resources:
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/util/peek_iterable.py", line 205, in next
    return self.__next__()
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/util/peek_iterable.py", line 210, in __next__
    item = self._NextItem()
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/util/peek_iterable.py", line 182, in _NextItem
    return next(self._iterable)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/lister.py", line 1046, in __call__
    utils.RaiseException(errors, ListException)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/utils.py", line 118, in RaiseException
    errors))
ListException: Some requests did not succeed:
 - Insufficient Permission

2018-03-09 04:05:23,101 ERROR    root            (gcloud.compute.forwarding-rules.list) Some requests did not succeed:
 - Insufficient Permission

